---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos/7

suites:
  - name: redmine.exz.su
    driver:
      vm_hostname: redmine.exz.su
      network:
        - ["private_network", {type: "dhcp"}]
    run_list:
      - recipe[chef_redmine::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
